#!/bin/bash
# Robusca — Correct Meta CLI Setup Script
# Verified package names — June 2026
# Run on MacBook Pro terminal: bash install_meta_cli.sh

set -e
echo "=== StudEx Meta CLI Setup (Robusca) ==="

# 1. Official Meta Marketing API Python SDK
echo "Installing facebook_business (official Meta Marketing API SDK)..."
pip3 install facebook_business

# 2. Meta Ads CLI (third-party CLI wrapper)
echo "Installing meta-ads-cli..."
pip3 install meta-ads-cli

# 3. Create credentials directory and env file
mkdir -p ~/.studex

cat > ~/.studex/meta.env << 'ENVEOF'
# StudEx Meta Credentials — generated by Robusca
# Fill in your values after getting them from Meta Business Manager

export META_ACCESS_TOKEN=""
export META_AD_ACCOUNT_ID="act_560666565541381"
export META_APP_ID="1649681979685968"
export META_PAGE_ID="108934711902801"
export INSTAGRAM_ID="17841403538967823"

# WhatsApp — get from developers.facebook.com/apps/1649681979685968/whatsapp-business/wa-dev-console
export WHATSAPP_PHONE_NUMBER_ID=""
export WHATSAPP_BUSINESS_ACCOUNT_ID=""
export WHATSAPP_TOKEN=""
ENVEOF

echo ""
echo "=== Done ==="
echo "Next: fill in tokens at ~/.studex/meta.env"
echo "Then run: source ~/.studex/meta.env"
echo ""
echo "Test WhatsApp (after filling tokens):"
cat << 'CURLEOF'
source ~/.studex/meta.env
curl -s -X POST "https://graph.facebook.com/v20.0/$WHATSAPP_PHONE_NUMBER_ID/messages" \
  -H "Authorization: Bearer $WHATSAPP_TOKEN" \
  -H "Content-Type: application/json" \
  -d '{"messaging_product":"whatsapp","to":"27279498737","type":"text","text":{"body":"Robusca test — StudEx OS live"}}'
CURLEOF
