#!/bin/bash
# Bootstrap war-room on Orgo VM — runs as a single curl call
set -e

VM="https://www.orgo.ai/api/computers/946b3156-cab9-4187-a94b-056dfab35105/bash"
H="Authorization: Bearer sk_live_a101a846ce4584ebe8bf81eda212f1ead12d9c0e6fa11ef2"
CT="Content-Type: application/json"

run() {
  echo "→ $1"
  curl -s -X POST "$VM" -H "$H" -H "$CT" -d "{\"command\": $(printf '%s' "$1" | python3 -c 'import sys,json; print(json.dumps(sys.stdin.read()))')}" 2>/dev/null | python3 -c 'import sys,json; d=sys.stdin.read(); print(d[:300])' 2>/dev/null || echo "(empty)"
  echo ""
}

# 1. Write .env
ENV=$(cat << 'ENVEOF'
# Studex Nest — Auto-generated by Robusca 2026-06-30
PORT=5000
HOST=0.0.0.0
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/studex_meat
SESSION_SECRET=studex_meat_session_secret_2026_change_in_production
SHOPIFY_STORE=studexmeat.myshopify.com
SHOPIFY_ADMIN_TOKEN=
ELEVENLABS_API_KEY=sk_93f872929e312224f4012da0709e8e18dfe53fdd0ae790b5
ORGO_COMPUTER_ID=946b3156-cab9-4187-a94b-056dfab35105
ORGO_API_KEY=sk_live_a101a846ce4584ebe8bf81eda212f1ead12d9c0e6fa11ef2
VM_IP=67.213.119.157
CHARLIE_PORT=3001
CHARLIE_WS_PORT=3002
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=studex_meat
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
N8N_URL=http://localhost:5678
OLLAMA_HOST=http://localhost:11434
MAXCLAW_URL=https://maxclaw-s7jwp.maxclaw.ai
MAXCLAW_TOKEN=rl_sk_0Uz1k7CegkXlN4w77ON8ZpiC_uc2DBpUBKLpWi6SGdM
AGENTMAIL_API_KEY=am_us_24fcb06c6b1babba88c56d49b1a83fc33f1b8acf153acf3ef905136f335e7502
AGENTMAIL_BASE_URL=https://api.agentmail.to/v0
DISCORD_BOT_TOKEN=
DISCORD_CLIENT_ID=
DISCORD_GUILD_ID=
DISCORD_LOG_CHANNEL_ID=
ALLOWED_USER_IDS=957514263586059
WAR_ROOM_URL=http://localhost:5000
APPROVAL_HOOK=http://localhost:3002/webhook
STUDEX_OS_PATH=/root/nest
GIT_REPO=https://github.com/TumeloRamaphosa/SrudEx-Agents-Nest-Cloud-VM.git
ENVEOF
)

echo "=== STEP 1: Write .env ==="
run "python3 -c \"import os; os.makedirs('/root/nest', exist_ok=True); open('/root/nest/.env', 'w').write($(printf '%s' "$ENV" | python3 -c 'import sys,json; print(json.dumps(sys.stdin.read()))')); print('ENV_OK')\""

echo "=== STEP 2: Check war-room structure ==="
run "ls /root/nest/war-room/ 2>/dev/null | head -10 && echo WAR_FOUND || echo WAR_MISSING"
run "test -d /root/nest/war-room/node_modules && echo NODE_OK || echo NODE_MISSING"
run "test -f /root/nest/war-room/dist/index.cjs && echo DIST_OK || echo DIST_MISSING"

echo "=== STEP 3: Kill old processes ==="
run "pkill -f war-room 2>/dev/null; pkill -f 'tsx' 2>/dev/null; echo KILLED"

echo "=== STEP 4: Start war-room in tmux ==="
run "tmux kill-session -t war-room 2>/dev/null; cd /root/nest/war-room && nohup npm run dev > /tmp/war-room.log 2>&1 & echo STARTED_PID: \$!"
