#!/usr/bin/env python3
"""Bootstrap war-room on the Orgo VM — one shot, no prompts."""
import urllib.request, urllib.error, json, time

VM = "https://www.orgo.ai/api/computers/946b3156-cab9-4187-a94b-056dfab35105/bash"
H = {"Authorization": "Bearer sk_live_a101a846ce4584ebe8bf81eda212f1ead12d9c0e6fa11ef2", "Content-Type": "application/json"}

def run(cmd, timeout=30):
    payload = json.dumps({"command": cmd}).encode()
    req = urllib.request.Request(VM, data=payload, headers=H, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.read().decode()
    except urllib.error.HTTPError as e:
        return f"HTTP {e.code}: {e.read().decode()[:200]}"
    except Exception as e:
        return f"ERR: {e}"

# ── .env content ──────────────────────────────────────────────────────────
env_content = f"""
# ── Studex Nest — Auto-generated by Robusca ─────────────────────────────
# Generated: 2026-06-30

# ── War Room ─────────────────────────────────────────────────────────────
PORT=5000
HOST=0.0.0.0
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/studex_meat
SESSION_SECRET=studex_meat_session_secret_2026_change_in_production

# ── Shopify ──────────────────────────────────────────────────────────────
SHOPIFY_STORE=studexmeat.myshopify.com
SHOPIFY_ADMIN_TOKEN={open('/workspace/TOOLS.md').read() if False else ''}
# NOTE: Set SHOPIFY_ADMIN_TOKEN manually — get from Shopify Admin → Apps → Develop apps

# ── ElevenLabs ───────────────────────────────────────────────────────────
ELEVENLABS_API_KEY=sk_93f872929e312224f4012da0709e8e18dfe53fdd0ae790b5

# ── Orgo / VM ────────────────────────────────────────────────────────────
ORGO_COMPUTER_ID=946b3156-cab9-4187-a94b-056dfab35105
ORGO_API_KEY=sk_live_a101a846ce4584ebe8bf81eda212f1ead12d9c0e6fa11ef2
VM_IP=67.213.119.157

# ── Charlie Orchestrator ──────────────────────────────────────────────────
CHARLIE_PORT=3001
CHARLIE_WS_PORT=3002

# ── PostgreSQL ────────────────────────────────────────────────────────────
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_DB=studex_meat
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres

# ── n8n ───────────────────────────────────────────────────────────────────
N8N_URL=http://localhost:5678

# ── Ollama ───────────────────────────────────────────────────────────────
OLLAMA_HOST=http://localhost:11434

# ── MaxClaw / OpenClaw ───────────────────────────────────────────────────
MAXCLAW_URL=https://maxclaw-s7jwp.maxclaw.ai
MAXCLAW_TOKEN=rl_sk_0Uz1k7CegkXlN4w77ON8ZpiC_uc2DBpUBKLpWi6SGdM

# ── AgentMail ────────────────────────────────────────────────────────────
AGENTMAIL_API_KEY=am_us_24fcb06c6b1babba88c56d49b1a83fc33f1b8acf153acf3ef905136f335e7502
AGENTMAIL_BASE_URL=https://api.agentmail.to/v0

# ── Discord ───────────────────────────────────────────────────────────────
DISCORD_BOT_TOKEN=
DISCORD_CLIENT_ID=
DISCORD_GUILD_ID=
DISCORD_LOG_CHANNEL_ID=
ALLOWED_USER_IDS=957514263586059

# ── War Room ─────────────────────────────────────────────────────────────
WAR_ROOM_URL=http://localhost:5000
APPROVAL_HOOK=http://localhost:3002/webhook

# ── Studex OS ─────────────────────────────────────────────────────────────
STUDEX_OS_PATH=/root/nest
GIT_REPO=https://github.com/TumeloRamaphosa/SrudEx-Agents-Nest-Cloud-VM.git
""".strip()

# Step 1: Write the .env file
print("1. Writing /root/nest/.env ...")
# Use python to write so quotes in env vars don't break shell
write_cmd = f"""python3 -c \"
import os
os.makedirs('/root/nest', exist_ok=True)
content = {repr(env_content)}
with open('/root/nest/.env', 'w') as f:
    f.write(content + chr(10))
print('ENV_WRITTED_OK')
\""""
r = run(write_cmd)
print("  →", r[:100].strip())

# Step 2: Check if war-room dist exists
print("\n2. Checking war-room build ...")
r = run("test -f /root/nest/war-room/dist/index.cjs && echo DIST_EXISTS || echo DIST_MISSING")
print("  →", r.strip())

# Step 3: Check if node_modules exists
print("\n3. Checking node_modules ...")
r = run("test -d /root/nest/war-room/node_modules && echo NODE_MODS_OK || echo NODE_MODS_MISSING")
print("  →", r.strip())

# Step 4: Kill any existing war-room process
print("\n4. Killing existing war-room processes ...")
r = run("pkill -f 'war-room' 2>/dev/null; pkill -f 'tsx' 2>/dev/null; echo KILLED")
print("  →", r.strip())

# Step 5: Start war-room in tmux
print("\n5. Starting war-room in tmux ...")
start_cmd = (
    "cd /root/nest/war-room && "
    "tmux kill-session -t war-room 2>/dev/null; "
    "tmux new-session -d -s war-room 'npm run dev' 2>&1; "
    "sleep 3 && "
    "tmux send-keys -t war-room C-c 2>/dev/null; "
    "echo TMUX_STARTED"
)
r = run(start_cmd, timeout=15)
print("  →", r.strip())

# Step 6: Wait for startup
print("\n6. Waiting 8s for startup ...")
time.sleep(8)

# Step 7: Check health
print("\n7. Health check ...")
r = run("curl -s http://localhost:5000/api/health 2>&1 | head -20 || echo HEALTH_FAILED")
print("  →", r[:200].strip())

# Step 8: Check port
print("\n8. Port check ...")
r = run("ss -tlnp 2>/dev/null | grep 5000 || netstat -tlnp 2>/dev/null | grep 5000 || echo PORT_CHECK_DONE")
print("  →", r[:200].strip())

print("\n" + "="*60)
print("DONE. War Room should be at: http://67.213.119.157:5000")
print("="*60)
